name: gain_guide
description: Personal workout tracker
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.4.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  provider: ^6.1.2
  sqflite: ^2.3.3+1
  path: ^1.9.0
  path_provider: ^2.1.4
  intl: ^0.20.2
  flutter_local_notifications: ^21.0.0
  flutter_timezone: ^5.0.2
  timezone: ^0.11.0
  google_sign_in: ^7.2.0
  sign_in_with_apple: ^8.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
