-- GainGuide hosted database foundation
-- Run this migration in the Supabase SQL editor.

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  display_name text not null default '',
  created_at timestamptz not null default now()
);

create table if not exists public.workouts (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  name text not null,
  scheduled_weekdays text,
  scheduled_hour integer check (scheduled_hour between 0 and 23),
  scheduled_minute integer check (scheduled_minute between 0 and 59),
  created_at timestamptz not null default now()
);

create table if not exists public.exercises (
  id bigint generated by default as identity primary key,
  workout_id bigint not null references public.workouts(id) on delete cascade,
  name text not null,
  target_sets integer not null default 3 check (target_sets > 0),
  min_reps integer not null default 8 check (min_reps >= 0),
  max_reps integer not null default 10 check (max_reps >= min_reps),
  rest_min_seconds integer not null default 90 check (rest_min_seconds >= 0),
  rest_max_seconds integer not null default 90 check (rest_max_seconds >= rest_min_seconds)
);

create table if not exists public.completed_workouts (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  name text not null,
  completed_at timestamptz not null default now()
);

create table if not exists public.completed_exercises (
  id bigint generated by default as identity primary key,
  workout_id bigint not null references public.completed_workouts(id) on delete cascade,
  name text not null
);

create table if not exists public.completed_set_entries (
  id bigint generated by default as identity primary key,
  exercise_id bigint not null references public.completed_exercises(id) on delete cascade,
  reps integer not null check (reps >= 0),
  weight double precision not null check (weight >= 0)
);

alter table public.profiles enable row level security;
alter table public.workouts enable row level security;
alter table public.exercises enable row level security;
alter table public.completed_workouts enable row level security;
alter table public.completed_exercises enable row level security;
alter table public.completed_set_entries enable row level security;

create policy "profiles_self" on public.profiles for all using (id = auth.uid()) with check (id = auth.uid());
create policy "workouts_self" on public.workouts for all using (user_id = auth.uid()) with check (user_id = auth.uid());
create policy "exercises_self" on public.exercises for all
using (exists (select 1 from public.workouts w where w.id = workout_id and w.user_id = auth.uid()))
with check (exists (select 1 from public.workouts w where w.id = workout_id and w.user_id = auth.uid()));
create policy "completed_workouts_self" on public.completed_workouts for all using (user_id = auth.uid()) with check (user_id = auth.uid());
create policy "completed_exercises_self" on public.completed_exercises for all
using (exists (select 1 from public.completed_workouts w where w.id = workout_id and w.user_id = auth.uid()))
with check (exists (select 1 from public.completed_workouts w where w.id = workout_id and w.user_id = auth.uid()));
create policy "completed_sets_self" on public.completed_set_entries for all
using (exists (
  select 1 from public.completed_exercises e
  join public.completed_workouts w on w.id = e.workout_id
  where e.id = exercise_id and w.user_id = auth.uid()
))
with check (exists (
  select 1 from public.completed_exercises e
  join public.completed_workouts w on w.id = e.workout_id
  where e.id = exercise_id and w.user_id = auth.uid()
));

create or replace function public.handle_new_user()
returns trigger language plpgsql security definer set search_path = public as $$
begin
  insert into public.profiles (id, display_name)
  values (new.id, coalesce(new.raw_user_meta_data ->> 'display_name', split_part(coalesce(new.email,''), '@', 1)));
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created after insert on auth.users
for each row execute procedure public.handle_new_user();
