create table if not exists public.set_entries (
  id bigint generated by default as identity primary key,
  exercise_id bigint not null references public.exercises(id) on delete cascade,
  reps integer not null check (reps >= 0),
  weight double precision not null check (weight >= 0)
);
alter table public.set_entries enable row level security;
create policy "sets_self" on public.set_entries for all
using (exists (
  select 1 from public.exercises e join public.workouts w on w.id=e.workout_id
  where e.id=exercise_id and w.user_id=auth.uid()
))
with check (exists (
  select 1 from public.exercises e join public.workouts w on w.id=e.workout_id
  where e.id=exercise_id and w.user_id=auth.uid()
));