-- Real two-way friend requests backed by Supabase.
create type public.friend_request_status as enum ('pending', 'accepted', 'declined');

create table public.friend_requests (
  id bigint generated by default as identity primary key,
  sender_id uuid not null references auth.users(id) on delete cascade,
  receiver_id uuid not null references auth.users(id) on delete cascade,
  status public.friend_request_status not null default 'pending',
  created_at timestamptz not null default now(),
  responded_at timestamptz,
  check (sender_id <> receiver_id)
);
create unique index friend_pair_unique on public.friend_requests
  (least(sender_id, receiver_id), greatest(sender_id, receiver_id));

alter table public.friend_requests enable row level security;
create policy "friend_requests_read" on public.friend_requests for select
using (auth.uid() = sender_id or auth.uid() = receiver_id);
create policy "friend_requests_send" on public.friend_requests for insert
with check (auth.uid() = sender_id and status = 'pending');
create policy "friend_requests_respond" on public.friend_requests for update
using (auth.uid() = receiver_id) with check (auth.uid() = receiver_id);

-- Users may discover profiles by email through this function without exposing auth.users.
create or replace function public.find_profile_by_email(search_email text)
returns table(id uuid, display_name text)
language sql security definer set search_path=public
as $$
  select p.id, p.display_name from public.profiles p
  join auth.users u on u.id=p.id
  where lower(u.email)=lower(trim(search_email)) and p.id<>auth.uid()
  limit 1;
$$;
revoke all on function public.find_profile_by_email(text) from public;
grant execute on function public.find_profile_by_email(text) to authenticated;
